type TokenList = list[tuple[str, int]]

NUMBERS: TokenList = [
    ("0", 0),
    ("1", 1),
    ("2", 2),
    ("3", 3),
    ("4", 4),
    ("5", 5),
    ("6", 6),
    ("7", 7),
    ("8", 8),
    ("9", 9),
]
"""The tokens used for representing numbers."""

OPERATORS: TokenList = [
    ("(", 10),
    (")", 11),
    ("^", 12),
    ("*", 13),
    ("/", 14),
    ("+", 15),
    ("-", 16),
    ("=", 17),
]
"""The tokens used for mathmatical operators."""

SYMBOLS: TokenList = [
    ("a", 18),
    ("b", 19),
    ("c", 20),
    ("d", 21),
    ("e", 22),
    ("f", 23),
    ("g", 24),
    ("h", 25),
    ("i", 26),
    ("j", 27),
    ("k", 28),
    ("l", 29),
    ("m", 30),
    ("n", 31),
    ("o", 32),
    ("p", 33),
    ("q", 34),
    ("r", 35),
    ("s", 36),
    ("t", 37),
    ("u", 38),
    ("v", 39),
    ("w", 40),
    ("x", 41),
    ("y", 42),
    ("z", 43),
    (" ", 44),
]
"""The tokens used for lower-case alphabet characters (upper-case is converted to lower-case)."""

COMMANDS: TokenList = [
    ("{start}", 45),
    ("{stop}", 46),
    ("{answer=}", 47),
    ("{=answer}", 48)
]
"""Miscellaneous "command" tokens that describe commands generated by the transformer model."""
