name: Run Tests

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup 'uv'
        uses: astral-sh/setup-uv@5
        with:
          version: "0.6.2"
          checksum: "37ea31f099678a3bee56f8a757d73551aad43f8025d377a8dde80dd946c1b7f2"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Run black.
        run: |
          out=$(uv run black --check --diff src/ test/)

          if [[ -n $out ]]; then
            echo "${out}"
            echo "\`\`\`python" >> $GITHUB_STEP_SUMMARY
            echo "${out}" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

            exit 1
          fi

      - name: Run tests
        run: |
          uv run pytest
