name: Run Tests

on: [pull_request]

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup 'uv'
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.2"
          checksum: "37ea31f099678a3bee56f8a757d73551aad43f8025d377a8dde80dd946c1b7f2"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Sync dependencies
        run: uv sync --only-dev

      - name: Run black
        run: uv run black --check src/ test/

      - name: Show formatting errors
        run: |
          out=$(uv run black --diff src/ test/)

          echo "${out}"
          echo "\`\`\`python" >> $GITHUB_STEP_SUMMARY
          echo "${out}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        if: ${{ failure() }}

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Setup 'uv'
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.2"
          checksum: "37ea31f099678a3bee56f8a757d73551aad43f8025d377a8dde80dd946c1b7f2"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Run PyTest
        run: |
          uv sync --extra cpu
          uv run pytest
